# Generated by Django 4.2.4 on 2023-08-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(default='coded', max_length=100),
            preserve_default=False,
        ),
    ]
